import { LegalDoc, LegalBlock } from "@/components/LegalDoc";

// Source: Dosed Privacy Policy, drafted to address GDPR/UK GDPR, CCPA/CPRA,
// and the Australian Privacy Act. Contact and data controller filled in for
// Shayan Asad (Eswatini).
const BLOCKS: LegalBlock[] = [
  { type: "p", text: "App: Dosed (\"Dosed\", \"we\", \"us\", \"our\")" },
  { type: "p", text: "Contact for privacy requests: liteishere@gmail.com" },
  { type: "p", text: "Data Controller: Shayan Asad, Eswatini" },

  { type: "h1", text: "1. Scope and applicable laws" },
  { type: "p", text: "This Policy is designed to comply with:" },
  { type: "li", text: "EU General Data Protection Regulation (GDPR)" },
  { type: "li", text: "UK GDPR and Data Protection Act 2018" },
  { type: "li", text: "California Consumer Privacy Act (CCPA) as amended by the California Privacy Rights Act (CPRA)" },
  { type: "li", text: "Australian Privacy Act 1988 and Australian Privacy Principles (APPs)" },
  { type: "li", text: "Other applicable data protection laws" },
  { type: "p", text: "Where local law provides stronger rights, those rights apply." },

  { type: "h1", text: "2. Personal information we collect" },
  { type: "h2", text: "A. Information you provide" },
  { type: "li", text: "Account data: email address, username, optional phone number, password (stored only as a one-way cryptographic hash)" },
  { type: "li", text: "Pet and medication content you create: pet names and details, medication names/schedules/dosages, dose logs" },
  { type: "li", text: "Pet photos you choose to upload" },
  { type: "li", text: "Communications you send to support" },
  { type: "h2", text: "B. Information collected automatically" },
  { type: "li", text: "Authentication and session data (access/refresh tokens, device tokens)" },
  { type: "li", text: "Security and audit events (login success/failure, password changes, session revocations, etc.), including IP address and user-agent associated with those events" },
  { type: "li", text: "Basic technical diagnostic data necessary to operate and secure the service" },
  { type: "h2", text: "C. Information we do not collect" },
  { type: "li", text: "Precise geolocation" },
  { type: "li", text: "Contacts, photos, or files beyond what you explicitly select" },
  { type: "li", text: "Payment card details (the App is currently free)" },
  { type: "li", text: "Sensitive personal information as defined under CCPA (we do not intentionally collect government ID, precise health diagnoses, biometric identifiers, etc.)" },

  { type: "h1", text: "3. How we use personal information" },
  { type: "p", text: "We use personal information only for the following purposes:" },
  { type: "li", text: "Providing and operating the App (account creation, authentication, data synchronisation across your devices, dose storage and reminders)" },
  { type: "li", text: "Sending essential service communications (email verification, password reset)" },
  { type: "li", text: "Security, fraud prevention, abuse detection, and maintaining an audit trail of security-relevant events" },
  { type: "li", text: "Complying with legal obligations" },
  { type: "li", text: "Improving reliability, performance, and security of the service (on aggregated or de-identified data where possible)" },
  { type: "p", text: "We do not use personal information for targeted advertising, sell it, or share it for cross-context behavioural advertising." },

  { type: "h1", text: "4. Legal bases for processing (GDPR / UK GDPR)" },
  { type: "li", text: "Performance of a contract — to provide the service you requested" },
  { type: "li", text: "Legitimate interests — security, fraud prevention, service integrity, and limited product improvement (balanced against your rights)" },
  { type: "li", text: "Consent — where required (e.g. optional phone number, photo upload). You may withdraw consent at any time" },
  { type: "li", text: "Legal obligation — where we must process or retain data to comply with law" },

  { type: "h1", text: "5. Disclosure of personal information" },
  { type: "p", text: "We disclose personal information as follows:" },
  { type: "li", text: "Service providers / processors who assist us in operating the App (cloud hosting, database, object storage for photos, email delivery). They are bound by contracts requiring them to process data only on our instructions and to implement appropriate security measures." },
  { type: "li", text: "Legal and safety reasons — when required by law, legal process, or to protect the rights, safety, or property of users, us, or the public" },
  { type: "li", text: "Business transfers — in connection with a merger, acquisition, or sale of assets, subject to appropriate confidentiality and continuity protections" },
  { type: "p", text: "We do not sell personal information. We do not share personal information for cross-context behavioural advertising." },

  { type: "h1", text: "6. International data transfers" },
  { type: "p", text: "Your information may be processed in countries other than your own. Where we transfer data from the EEA, UK, or other regions with transfer restrictions, we use appropriate safeguards such as:" },
  { type: "li", text: "European Commission Standard Contractual Clauses (SCCs)" },
  { type: "li", text: "UK International Data Transfer Agreement / Addendum" },
  { type: "li", text: "Other legally recognised transfer mechanisms" },

  { type: "h1", text: "7. Data retention" },
  { type: "li", text: "Account and content data are retained while your account remains active." },
  { type: "li", text: "After you delete your account we permanently delete or irreversibly anonymise your personal data within a reasonable period (typically 30–90 days), except where longer retention is required by law (e.g. security audit logs)." },
  { type: "li", text: "Soft-deleted records may persist briefly to enable synchronisation across your devices before permanent removal." },
  { type: "li", text: "Pet photos are deleted on a best-effort basis when the associated pet or account is deleted." },

  { type: "h1", text: "8. Security" },
  { type: "p", text: "We implement technical and organisational measures including:" },
  { type: "li", text: "Password hashing with modern algorithms" },
  { type: "li", text: "Short-lived access tokens and rotating, hashed refresh tokens with reuse detection" },
  { type: "li", text: "Encryption in transit (TLS)" },
  { type: "li", text: "Private object storage for photos with authenticated, account-scoped access" },
  { type: "li", text: "Rate limiting, account lockout after repeated failed logins, and an immutable security audit log" },
  { type: "li", text: "Access controls and monitoring" },
  { type: "p", text: "No method of transmission or storage is 100% secure. We continually work to protect your information." },

  { type: "h1", text: "9. Your rights" },
  { type: "h2", text: "A. Rights under GDPR / UK GDPR (EEA and UK users)" },
  { type: "p", text: "You have the right to:" },
  { type: "li", text: "Access your personal data" },
  { type: "li", text: "Rectify inaccurate data" },
  { type: "li", text: "Erasure (\"right to be forgotten\")" },
  { type: "li", text: "Restrict processing" },
  { type: "li", text: "Data portability" },
  { type: "li", text: "Object to processing based on legitimate interests" },
  { type: "li", text: "Withdraw consent at any time (without affecting prior processing)" },
  { type: "li", text: "Lodge a complaint with your local supervisory authority (e.g. ICO in the UK, or your EU member state authority)" },
  { type: "h2", text: "B. Rights under CCPA/CPRA (California residents)" },
  { type: "p", text: "You have the right to:" },
  { type: "li", text: "Know the categories and specific pieces of personal information we collect, use, and disclose" },
  { type: "li", text: "Delete personal information we hold about you (subject to certain exceptions)" },
  { type: "li", text: "Correct inaccurate personal information" },
  { type: "li", text: "Opt out of the \"sale\" or \"sharing\" of personal information (we do not sell or share for cross-context behavioural advertising)" },
  { type: "li", text: "Limit the use and disclosure of sensitive personal information (we do not use sensitive personal information for purposes that would trigger this right)" },
  { type: "li", text: "Non-discrimination for exercising your privacy rights" },
  { type: "p", text: "We do not sell personal information or share it for cross-context behavioural advertising. We do not have actual knowledge that we sell or share the personal information of consumers under 16." },
  { type: "h2", text: "C. Rights under the Australian Privacy Act" },
  { type: "p", text: "You have the right to:" },
  { type: "li", text: "Access personal information about you" },
  { type: "li", text: "Request correction of inaccurate, out-of-date, incomplete, or misleading information" },
  { type: "li", text: "Make a complaint about how we handle your personal information" },
  { type: "h2", text: "How to exercise your rights" },
  { type: "p", text: "Email us at liteishere@gmail.com. We will verify your request and respond within the timeframes required by applicable law (generally 30–45 days, extendable where permitted). You may also delete your account directly in the App settings where that feature is available." },

  { type: "h1", text: "10. Children's privacy" },
  { type: "p", text: "The App is not directed at children under 16 (or the applicable age of digital consent). We do not knowingly collect personal information from children under 16. If we learn that we have collected such information, we will delete it. Parents or guardians who believe a child has provided us with personal information should contact us immediately." },

  { type: "h1", text: "11. Local device processing and notifications" },
  { type: "p", text: "Dose reminders are scheduled and displayed as local notifications on your device. We do not receive the notification content itself." },

  { type: "h1", text: "12. Do Not Track / Global Privacy Control" },
  { type: "p", text: "We do not track users across third-party websites or apps for advertising purposes. Because we do not engage in such tracking or in the \"sale\"/\"sharing\" of personal information, we do not respond to browser Do Not Track signals in a special manner. California residents may exercise their rights as described above." },

  { type: "h1", text: "13. Changes to this Privacy Policy" },
  { type: "p", text: "We may update this Policy from time to time. The \"Last updated\" date will be revised, and material changes will be communicated through the App or by email where applicable. Continued use of the App after the effective date of changes constitutes acceptance of the updated Policy, except where applicable law requires additional consent." },

  { type: "h1", text: "14. Contact and complaints" },
  { type: "p", text: "Privacy requests and questions: liteishere@gmail.com" },
  { type: "p", text: "EU/UK supervisory authority: you may lodge a complaint with your local data protection authority." },
  { type: "p", text: "Australia: you may complain to the Office of the Australian Information Commissioner (OAIC)." },
  { type: "p", text: "California: you may contact the California Privacy Protection Agency or the California Attorney General." },
];

export default function PrivacyPolicy() {
  return <LegalDoc updated="12 September 2026" blocks={BLOCKS} />;
}
