/**
 * 150 playful, kid-friendly one-liners shown on the Pets screen. One is
 * picked per clock hour (local time), so it changes on the hour and stays
 * the same for anyone who opens the app within that hour.
 *
 * The hour number is multiplied by 7 before wrapping: 7 shares no factor
 * with 150, so every quote is shown exactly once per 150 hours (no repeats
 * for over 6 days) but the order looks shuffled instead of alphabetical
 * "next one, next one".
 */
export const QUOTES: string[] = [
  "Zoomies are just happiness with nowhere to park.",
  "Boop! You found the secret button.",
  "Naps are a very serious job. Pets take it seriously.",
  "Wag first, ask questions later.",
  "Today's forecast: 100% chance of snuggles.",
  "Every day is a good day to bring a stick home.",
  "Belly rubs are the original hug.",
  "Tiny paws, giant feelings.",
  "If it fits, it sits. If it doesn't fit, it sits anyway.",
  "Purring is a tiny engine powered by love.",
  "Sniff, sniff... ooooh, what's THAT smell?",
  "The floor is lava, but the sofa is a cloud.",
  "Sleeping in a sunbeam totally counts as a hobby.",
  "Best friends come with fur and cold noses.",
  "A wagging tail is a happy little flag.",
  "Home is wherever your pet is waiting.",
  "Treat time is the best time.",
  "Tiny dose, big hero.",
  "Every dose given is a gold star.",
  "You remembered the medicine. That's superhero stuff.",
  "Ta-da! Dose done!",
  "A sticker for the brave patient. A sticker for the brave human, too.",
  "Pill on time, tail up high.",
  "Healthy pets, happy hearts.",
  "You're the hero in your pet's story.",
  "If clouds were fluffy dogs, the sky would be very noisy.",
  "Puddles are tiny swimming pools for boots.",
  "Ask a pet about their day and they'll say, \"Best. Day. Ever.\"",
  "Bubbles are just floating giggles.",
  "Somewhere, a puppy is discovering its own tail. Again.",
  "The moon is a giant nightlight for cats.",
  "Socks are for stealing. That's the rule.",
  "Blankets were invented so pets could build forts.",
  "Cardboard boxes are palaces in disguise.",
  "A squeaky toy is a pocket-sized orchestra.",
  "Why did the dog sit in the shade? He didn't want to be a hot dog!",
  "What's a cat's favorite color? Purr-ple!",
  "Why did the cat sit on the computer? To keep an eye on the mouse!",
  "What do you call a cold dog? A chili dog!",
  "What did the puppy say when it sat on sandpaper? Ruff!",
  "What do you call a pile of kittens? A meowntain!",
  "Why was the cat so good at the game? It had nine lives!",
  "What do you call a dog magician? A labracadabrador!",
  "Where do pets go when they lose their tails? A re-tail store!",
  "What do you call a sleeping pup? A bull-dozer!",
  "Fetch is just running in circles with extra steps.",
  "Every walk is an adventure if you sniff hard enough.",
  "Wiggle your whole bum when you're happy. Those are the rules.",
  "The best part of any door is the moment it opens for a pet.",
  "A pet's superpower: making the whole room smile.",
  "Some days are for zoomies. Some days are for loafing. Both are perfect.",
  "Pet the dog. Pet the cat. Pet the day.",
  "Meow means \"hello,\" \"feed me,\" and \"I love you,\" all at once.",
  "Woof means \"you're home!\" every single time.",
  "Whiskers twitch when the good dreams start.",
  "Tummy up means \"I trust you a whole bunch.\"",
  "A head bonk from a cat is a high five with feelings.",
  "Paws are basically tiny slippers that never come off.",
  "Growing up is optional. Playing is forever.",
  "Jump in puddles. Roll in leaves. Chase the wind.",
  "Be the kind of person your pet thinks you are.",
  "Feed the fish, water the plants, hug the cat.",
  "Small pets, big personalities.",
  "Hamsters are just tiny pockets of energy on wheels.",
  "Bunnies are cloud-hoppers with fluffy tails.",
  "Birds sing because mornings are exciting.",
  "Fish blow bubbles because they love telling secrets.",
  "A turtle's home is a very slow, very cozy backpack.",
  "Snails are proof that you can go anywhere, eventually.",
  "Every pet has a favorite spot. Finding it is half the fun.",
  "The couch cushion nearest your pet is officially theirs.",
  "Cuddles are free and always in season.",
  "Naps are just charging time for the next big adventure.",
  "A pet's day: nap, snack, nap, adventure, snack, nap.",
  "Some heroes wear capes. Some heroes wear fur.",
  "You're doing great, sweet human. Keep going!",
  "Give your pet a smile today. They'll smile back in wags.",
  "Sunbeams travel across the floor. Pets follow them, obviously.",
  "Curiosity didn't hurt the cat. It gave the cat a very good time.",
  "Dogs know a good day when they hear the leash jingle.",
  "Cats know a good day when the sunbeam arrives.",
  "A window is a pet's TV. Squirrels are the best show.",
  "Sit. Stay. Good pet! Now go be silly.",
  "Hugs are best when they're wiggly.",
  "Warm blankets and warm hearts are the coziest pair.",
  "Big yawns are catching. Try one right now.",
  "Cold noses are nature's little doorbells.",
  "Spin three times, plop down. That's how the best beds are made.",
  "Ears up means \"I heard something wonderful!\"",
  "Slow blinks from a cat mean \"I like you a lot.\"",
  "The first thing a puppy learns: everything is exciting.",
  "Kittens: because chaos should come with tiny paws.",
  "Seniors know the best napping spots. Ask them.",
  "Every pet deserves a name that makes them wiggle.",
  "Adventure is out there, and it smells amazing.",
  "A day without a cuddle is a day that needs a redo.",
  "Tail chasing is a perfectly good way to spend the afternoon.",
  "When in doubt, do a happy dance.",
  "The best toy is the one that wasn't a toy five minutes ago.",
  "Fluffy is a feeling, and pets are full of it.",
  "Pets don't count days. They count snuggles.",
  "Keep calm and pet on.",
  "Go slow. Sniff around. Enjoy the walk.",
  "Every tail has a story. Most of them are about snacks.",
  "Your pet thinks you hung the moon. Let them keep believing.",
  "One tiny paw print can fill a whole heart.",
  "Your pet is your very own comfy corner of the world.",
  "Let's play a game! It's called \"let's play a game.\"",
  "Warm lap, soft purr, nothing else needed.",
  "Chasing lasers is a very serious full-time job.",
  "A good stretch is a pet's morning coffee.",
  "Sometimes the best plan is a nap on the plan.",
  "There's always room for one more cuddle.",
  "Hooray for the small things, like a good scratch behind the ears!",
  "Dance like nobody's watching, except maybe your dog.",
  "Chirp, meow, woof, squeak: it all means \"hi!\"",
  "Treasure hunt: find the toy under the sofa. Again.",
  "A pet's favorite words: \"Wanna go?\"",
  "Keep your friends close and your pets closer.",
  "You're the reason someone's tail is wagging today.",
  "Be silly. Be soft. Be somebody's favorite human.",
  "Little steps, little paws, big smiles.",
  "Every hero needs a sidekick. Yours has whiskers.",
  "Some kisses are wet. All of them are love.",
  "Let the small stuff go. Except the ball. Never the ball.",
  "Time for snuggles? It's always time for snuggles.",
  "A great day starts with a great stretch.",
  "Best nap ever, part 47.",
  "Tomorrow's plan: more of today's fun.",
  "Wiggle, waggle, wiggle, waggle. Repeat.",
  "Snacks are just love in a crunchy shape.",
  "Feels like a good day for a good boy or a good girl.",
  "Pawsitively wonderful, that's you.",
  "You're purr-fect just as you are.",
  "Let's do this thing, one paw at a time.",
  "Someone in your house believes you're magic.",
  "Keep smiling. It makes tails wag.",
  "Time flies when you're chasing your own tail.",
  "Hooray for another day with your favorite furry friend!",
  "Be brave like a puppy at the vet's door.",
  "Tiny victories: a wagging tail, a happy purr, a dose done.",
  "Take a deep breath. Give a gentle pat. Feel better.",
  "Small hearts beat fast for the people they love.",
  "Bedtime for pets: circle, circle, flop.",
  "Play now, nap later, snuggle always.",
  "Pet parents are just grown-ups with the best jobs.",
  "Look at you, taking such good care!",
  "The best part of medicine time? The cuddle after.",
  "Be kind, be gentle, be a soft place to land.",
  "The world is a better place with paw prints on it."
];

/** Whole hours since the epoch, in the device's local time — ticks over at :00 local. */
export function hourIndex(d: Date = new Date()): number {
  return Math.floor((d.getTime() - d.getTimezoneOffset() * 60000) / 3600000);
}

export function quoteForHour(hour: number): { index: number; text: string } {
  const n = QUOTES.length;
  const index = (((hour * 7) % n) + n) % n;
  return { index, text: QUOTES[index] };
}
